name: PHP Insights

on:
  push:
    branches:
      - 'develop'

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run:
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys:
            ${{ runner.os }}-composer-
      - name: Require php-cs-fixer
        run: composer require nunomaduro/phpinsights --dev
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - run:
          php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"
      - name: PHP Insights
        run:
          php artisan insights -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80 --disable-security-check
